constantsPreset: Default
distFile: flower/flower.exe
# forceResolution:
#   width: 1920
#   height: 1080
globals:
  float:
  - hash
  - stepIndex
  - TAU = 6.28
shaderFile: shader.stoy
uniforms:
  - Beat
  - EndCameraAnglesX
  - EndCameraAnglesY
  - EndCameraAnglesZ
  - EndCameraPositionX
  - EndCameraPositionY
  - EndCameraPositionZ
  - EndSeedPositionX
  - EndSeedPositionY
  - EndSeedPositionZ
  - StartCameraAnglesX
  - StartCameraAnglesY
  - StartCameraAnglesZ
  - StartCameraPositionX
  - StartCameraPositionY
  - StartCameraPositionZ
  - StartSeedPositionX
  - StartSeedPositionY
  - StartSeedPositionZ
  - StartEndRatio
