# capture:
#   width: 1280
#   height: 720
#   fps: 30
#   duration: 128
constantsPreset: Default
distFile: those-who-leave-by-koltes-ponk-unix/those-who-leave.exe
# forceResolution:
#   width: 1920
#   height: 1080
globals:
  float:
  - currentHeight
  - hash
  - stepIndex
  - TAU = 6.283
shaderFile: shader.stoy
uniforms:
  - Beat
  - EndCameraAnglesX
  - EndCameraAnglesY
  - EndCameraAnglesZ
  - EndCameraPositionX
  - EndCameraPositionY
  - EndCameraPositionZ
  - EndSeedPositionX
  - EndSeedPositionY
  - EndSeedPositionZ
  - StartCameraAnglesX
  - StartCameraAnglesY
  - StartCameraAnglesZ
  - StartCameraPositionX
  - StartCameraPositionY
  - StartCameraPositionZ
  - StartSeedPositionX
  - StartSeedPositionY
  - StartSeedPositionZ
  - StartEndRatio
