constantsPreset: Dist
distFile: flower/flower.exe
shaderFile: shader.stoy
uniforms:
  - beat
  - endCameraAnglesX
  - endCameraAnglesY
  - endCameraAnglesZ
  - endCameraPositionX
  - endCameraPositionY
  - endCameraPositionZ
  - startCameraAnglesX
  - startCameraAnglesY
  - startCameraAnglesZ
  - startCameraPositionX
  - startCameraPositionY
  - startCameraPositionZ
  - startEndRatio
  - synth_Height
  - synth_Width
